server:
  port: 8083

spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/ecommerce-order-db

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce-realm
          jwk-set-uri: http://localhost:8080/realms/ecommerce-realm/protocol/openid-connect/certs

application:
  config:
    product-service-url: http://localhost:8081
    crm-service-url: http://localhost:8082