server:
  port: 8084
spring:
  application:
    name: discovery-media-service
  servlet:
    multipart:
      max-file-size: 50MB       # Kısa videolar için üst limit
      max-request-size: 55MB
  spring:
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8080/realms/ecommerce-realm
            jwk-set-uri: http://localhost:8080/realms/ecommerce-realm/protocol/openid-connect/certs
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadminpassword
  region: us-east-1             # MinIO için varsayılan
  buckets:
    videos: reels-videos
    thumbnails: reels-thumbnails
application:
  clients:
    product-catalog:
      url: http://localhost:8081
    order:
      url: http://localhost:8083