server:
  port: 8081

spring:
  application:
    name: product-catalog-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/product_catalog_db
  # --- Keycloak Entegrasyonu ---
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce-realm
          jwk-set-uri: http://localhost:8080/realms/ecommerce-realm/protocol/openid-connect/certs

# --- MinIO Object Storage Entegrasyonu ---
minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadminpassword
  bucket-name: product-images

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security: DEBUG